HOST = x86_64-w64-mingw32
CC = $(HOST)-gcc
CXX = $(HOST)-g++
AR = $(HOST)-ar rcs
RANLIB = $(HOST)-ranlib

CFLAGS = -Wall -fPIC -DPIC -g -O2
LDFLAGS = -lssp
DFLAGS = -shared
CFLAGS += -DWEBRTC_WIN

OS = mingw
ARCH = x86_64
DYEXT = dll
EXEXT = exe


JDK_HOME = $(WIN_JDK)
CFLAGS += -I$(JDK_HOME)/include
CFLAGS += -I$(JDK_HOME)/include/windows

OPUS_INC = -Iopus-1.3.1/include
INCLUDE += $(OPUS_INC)

OPUS_LIB = -Lopus-1.3.1/build/.libs -lopus
LDFLAGS += $(OPUS_LIB)


include common.mak
